[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["google-labs-jules[bot] <161369871+google-labs-jules[bot]@users.noreply.github.com>"]
readme = "README.md"
packages = [{ include = "src" }]

[tool.poetry.dependencies]
python = "^3.14"
librosa = "^0.10.1"
mido = "^1.3.2"
pyaudio = "*"
Flask = "^3.0.2"
numpy = "^2.0.0"
requests = "^2.32.3"
flask-cors = "^4.0.0"
sqlalchemy = "^2.0.28"
pedalboard = "^0.9.14"
amanuensis = { git = "https://github.com/HarringAudioTech/amanuensis.git", branch = "trunk" }
patchlab = { git = "https://github.com/HarringAudioTech/patchlab.git", rev = "567eaf9", subdirectory = "patchlab-python" }

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"
pylint = ">=3.3.7,<4.0.0"
black = ">=26.3.1"
autopep8 = ">=2.3.2,<3.0.0"
pre-commit = "^4.2.0"
flake8 = "^7.2.0"
pytest-mock = "*"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
