import os
import logging
from typing import Any, Dict, List, Optional
from sqlalchemy.orm import Session

from src.core.processing_stages import AudioProcessingStage, DATA_TYPE_LIST_OF_SAMPLE_DATA, DATA_TYPE_FILE_PATH
from src.core.stage_runner import register_stage
from src.core.dspreset_generator import DecentSamplerPresetGenerator
from src.core.instrument_data import InstrumentData
from src.core.project import Project as CoreProject # Alias to avoid conflict with database.models.Project

logger = logging.getLogger(__name__)

class DecentSamplerExportStage(AudioProcessingStage):
    """
    An audio processing stage that generates a Decent Sampler (.dspreset) file
    from the samples associated with a recording.
    """

    @property
    def name(self) -> str:
        return "decent_sampler_export"

    @property
    def description(self) -> str:
        return "Generates a Decent Sampler (.dspreset) instrument from processed samples."

    @property
    def input_type(self) -> str:
        # This stage doesn't directly process audio data, but rather uses metadata
        # from previously generated samples. We can make its input type flexible
        # or define a new type if needed. For now, let's assume it receives
        # a list of sample data (even if it's just a trigger to start).
        return DATA_TYPE_LIST_OF_SAMPLE_DATA # Or DATA_TYPE_FILE_PATH if it's the first stage

    @property
    def output_type(self) -> str:
        return DATA_TYPE_FILE_PATH # Path to the generated .dspreset file

    @property
    def default_params(self) -> Dict[str, Any]:
        return {
            "instrument_name": "New Decent Sampler Instrument",
            "instrument_author": "Generated by Orchestrator",
            "instrument_version": "1.0.0",
            "ui_background_image_path": None, # Optional path to a UI background image
        }

    def process(
        self, data: Any, params: Dict[str, Any], context: Optional[Dict[str, Any]] = None
    ) -> str:
        logger.info(f"[{self.name}] Stage starting. Params: {params}, Context keys: {list(context.keys() if context else [])}")

        if not context:
            raise ValueError("Context is required and was not provided.")
        
        db_session: Session = context.get("db_session")
        project_id: int = context.get("project_id")
        recording_id: int = context.get("recording_id")
        output_sample_dir: str = context.get("output_sample_dir") # This is where samples were saved

        if not all([db_session, project_id, recording_id, output_sample_dir]):
            raise ValueError("Missing required context keys for DecentSamplerExportStage.")

        # Load the CoreProject to access samples associated with the recording
        core_project = CoreProject(project_id=project_id)

        # Prepare InstrumentData from parameters
        instrument_data = InstrumentData(
            name=params.get("instrument_name"),
            author=params.get("instrument_author"),
            version=params.get("instrument_version"),
            ui_background_image_path=params.get("ui_background_image_path"),
        )

        # The output_sample_dir from context is where the samples for this run are stored.
        # The DecentSamplerPresetGenerator will copy samples from their original location
        # (as stored in SampleModel.file_path) to the instrument's Samples directory.
        # We need to ensure the output_base_dir for the generator is appropriate.
        # Let's create a specific output directory for the .dspreset file within the project's output.
        
        # Assuming output_sample_dir is something like data/projects/project_X/recording_Y/output_suffix
        # We want the .dspreset to be in data/projects/project_X/recording_Y/output_suffix/instrument_name_sanitized
        instrument_name_sanitized = instrument_data.name.replace(" ", "_").lower()
        dspreset_output_base_dir = os.path.join(output_sample_dir, instrument_name_sanitized)

        # Initialize and run the generator
        generator = DecentSamplerPresetGenerator(
            project=core_project,
            instrument_data=instrument_data,
            output_base_dir=output_sample_dir # Generator expects the base dir where the instrument folder will be created
        )
        
        # The generate_preset method prints its output, but doesn't return the path.
        # We need to infer it or modify generate_preset to return it.
        # For now, let's infer it based on the generator's logic.
        generator.generate_preset()

        # Infer the path to the generated .dspreset file
        generated_dspreset_filename = f"{instrument_name_sanitized}.dspreset"
        generated_dspreset_path = os.path.join(dspreset_output_base_dir, generated_dspreset_filename)

        if not os.path.exists(generated_dspreset_path):
            logger.error(f"[{self.name}] Failed to find generated .dspreset file at {generated_dspreset_path}")
            raise RuntimeError(f"Failed to generate Decent Sampler preset.")

        logger.info(f"[{self.name}] Decent Sampler preset generated at: {generated_dspreset_path}")
        return generated_dspreset_path

# Register the stage
try:
    register_stage(DecentSamplerExportStage)
except Exception as e:
    logger.critical(f"Failed to register DecentSamplerExportStage: {e}", exc_info=True)
