import os
import logging
from typing import Any, Optional, Dict, Union
from pathlib import Path

class ProjectManager:
    """
    Manages project-related utilities, such as directory structures.
    """

    DEFAULT_UPLOAD_BASE_DIR = "data/uploads"

    @classmethod
    def get_project_upload_dir(cls, project_id: int, app_config: Any) -> str:
        """
        Determines the upload directory for a given project.

        Args:
            project_id (int): The ID of the project.
            app_config (dict): The Flask application configuration object.
                               Expected to behave like a dictionary.

        Returns:
            str: The absolute or relative path to the project's upload directory.
        """
        upload_base_dir = app_config.get("UPLOAD_FOLDER", cls.DEFAULT_UPLOAD_BASE_DIR)
        project_specific_dir = f"project_{project_id}"
        return os.path.join(upload_base_dir, project_specific_dir)

    @classmethod
    def get_project_dir(cls, project_id: int, app_config: Optional[Dict[str, Any]] = None) -> Path:
        """
        Returns the path to the project's data directory.
        """
        base_dir = "data/projects"
        if app_config:
            base_dir = app_config.get("PROJECTS_BASE_DIR", base_dir)
        return Path(base_dir) / f"project_{project_id}"
        
    @classmethod
    def create_project_directory(
        cls, 
        project_id: int, 
        project_type: str, 
        app_config: Optional[Dict[str, Any]] = None,
        base_dir: Optional[Union[str, Path]] = None
    ) -> str:
        """
        Creates the directory structure for a new project.
        
        For virtual_instrument projects, creates additional subdirectories for samples,
        presets, and exports. For sample_pack projects, creates a simpler structure.
        
        Args:
            project_id: The ID of the project
            project_type: Type of project ('sample_pack' or 'virtual_instrument')
            app_config: Optional Flask app config (used to get base directories)
            base_dir: Optional base directory to use instead of getting from app_config
            
        Returns:
            str: Path to the created project directory
            
        Raises:
            OSError: If directory creation fails
            ValueError: If project_type is invalid
        """
        if project_type not in ["sample_pack", "virtual_instrument", "construction_kit"]:
            raise ValueError(f"Invalid project_type: {project_type}. Must be 'sample_pack', 'virtual_instrument', or 'construction_kit'")
            
        # Determine base directory
        if base_dir is None and app_config is not None:
            base_dir = app_config.get("PROJECTS_BASE_DIR", "data/projects")
        elif base_dir is None:
            base_dir = "data/projects"
            
        # Convert to Path object if it's a string
        base_path = Path(base_dir) if isinstance(base_dir, str) else base_dir
        
        # Create project directory
        project_dir = base_path / f"project_{project_id}"
        project_dir.mkdir(parents=True, exist_ok=True)
        
        # Create project type specific directories
        if project_type == "virtual_instrument":
            # Virtual instrument project structure
            (project_dir / "samples").mkdir(exist_ok=True)
            (project_dir / "samples" / "raw").mkdir(exist_ok=True)
            (project_dir / "samples" / "processed").mkdir(exist_ok=True)
            (project_dir / "samples" / "mapped").mkdir(exist_ok=True)
            (project_dir / "presets").mkdir(exist_ok=True)
            (project_dir / "exports").mkdir(exist_ok=True)
            (project_dir / "midi").mkdir(exist_ok=True)
            (project_dir / "metadata").mkdir(exist_ok=True)
        else:
            # Sample pack project structure
            (project_dir / "samples").mkdir(exist_ok=True)
            (project_dir / "exports").mkdir(exist_ok=True)
            (project_dir / "midi").mkdir(exist_ok=True)
            
        # Create a README file with project info
        readme_path = project_dir / "README.md"
        with open(readme_path, 'w') as f:
            f.write(f"# Project {project_id}\n")
            f.write(f"Type: {project_type}\n")
            f.write("\nThis directory was automatically generated by Sample Orchestrator.\n")
        
        # Set permissions (read/write for owner, read for others)
        project_dir.chmod(0o755)
        
        logging.info(f"Created project directory at: {project_dir}")
        return str(project_dir)
