name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      POETRY_EXPERIMENTAL_SYSTEM_GIT_CLIENT: "true"
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      run: |
        pip install poetry
    - name: Install PortAudio system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libportaudio2 libportaudiocpp0 portaudio19-dev
    - name: Configure Git and Poetry
      run: |
        git config --global url."https://${{ secrets.GH_PAT }}@github.com/".insteadOf "https://github.com/"
        poetry config system-git-client true
    - name: Install dependencies
      run: |
        poetry install

    - name: Analysing the code with pylint
      run: |
        poetry run pylint $(git ls-files '*.py')
