# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

permissions:
  contents: read
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install Poetry
      run: |
        pip install poetry
    - name: Install PortAudio system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libportaudio2 libportaudiocpp0 portaudio19-dev
    - name: Install dependencies
      run: |
        poetry install
    - name: Test with pytest
      run: |
        poetry run pytest --cov=src --cov-report=xml:coverage.xml
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.xml
    - name: Publish Coverage Check
      uses: MADLAD/publish-coverage-check@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        coverage_file: coverage.xml
        coverage_type: cobertura # pytest-cov's XML format is cobertura
        comment_title: 'Code Coverage Report'
        min_coverage_overall: 0 # We don't want to fail the check based on overall coverage
        min_coverage_new: 0 # We don't want to fail based on new code coverage
        # The following are important for reporting changes
        comment_on_changed_files: true
        # Ensure this action has permissions to write to PRs.
        # The main workflow permissions might need `pull-requests: write`.
