# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      POETRY_EXPERIMENTAL_SYSTEM_GIT_CLIENT: "true"

    steps:
    - uses: actions/checkout@v4
    - name: Checkout amanuensis
      uses: actions/checkout@v4
      with:
        repository: HarringAudioTech/amanuensis
        token: ${{ secrets.GH_PAT }}
        path: amanuensis
        ref: trunk
    - name: Checkout patchlab
      uses: actions/checkout@v4
      with:
        repository: HarringAudioTech/patchlab
        token: ${{ secrets.GH_PAT }}
        path: patchlab

    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install Poetry
      run: |
        pip install poetry poetry-plugin-export
    - name: Install PortAudio system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libportaudio2 libportaudiocpp0 portaudio19-dev
    - name: Install dependencies
      run: |
        poetry export --without-hashes --with dev -f requirements.txt > requirements.txt
        sed -i '/amanuensis/d' requirements.txt
        sed -i '/patchlab/d' requirements.txt
        pip install -r requirements.txt
        pip install ./amanuensis
        pip install ./patchlab/patchlab-python
        pip install -e .


    - name: Test with pytest
      run: |
        pytest
  
