# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install Poetry
      run: |
        pip install poetry
    - name: Install PortAudio system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libportaudio2 libportaudiocpp0 portaudio19-dev
    - name: Configure Git credentials
      run: |
        git config --global credential.helper 'store --file=/home/runner/.git-credentials'
        echo "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com" > /home/runner/.git-credentials
    - name: Install dependencies
      run: |
        poetry install
    - name: Test with pytest
      run: |
        poetry run pytest
  
